export const garageRequests = [
    {
        garageName: "QuickFix Garage",
        ownerName: "Jane Smith",
        servicesRequested: ["Oil Change", "Tire Rotation"],
        tirePurchased: true,
        status: "Completed",
        requestedTime: "2024-10-01T11:26:49.508Z",
    },
    {
        garageName: "AutoPro Garage",
        ownerName: "John Doe",
        servicesRequested: ["Brake Inspection"],
        tirePurchased: false,
        status: "Pending",
        requestedTime: "2024-10-02T11:26:49.508Z",
    },
    {
        garageName: "Speedy Repairs",
        ownerName: "Alice Johnson",
        servicesRequested: ["Tire Rotation", "Battery Replacement"],
        tirePurchased: true,
        status: "Cancelled",
        requestedTime: "2024-09-03T11:26:49.508Z",
    },
    {
        garageName: "Elite Garage",
        ownerName: "Bob Brown",
        servicesRequested: ["Oil Change"],
        tirePurchased: false,
        status: "Completed",
        requestedTime: "2024-09-04T11:26:49.508Z",
    },
    {
        garageName: "Reliable Repairs",
        ownerName: "Carol White",
        servicesRequested: ["Brake Inspection", "Tire Rotation"],
        tirePurchased: true,
        status: "Received",
        requestedTime: "2024-09-05T11:26:49.508Z",
    },
    {
        garageName: "Neighborhood Garage",
        ownerName: "David Black",
        servicesRequested: ["Oil Change", "Tire Purchase"],
        tirePurchased: true,
        status: "Completed",
        requestedTime: "2024-10-06T11:26:49.508Z",
    },
    {
        garageName: "Fast Lane Garage",
        ownerName: "Emma Green",
        servicesRequested: ["Tire Rotation", "Oil Change"],
        tirePurchased: false,
        status: "Cancelled",
        requestedTime: "2024-09-07T11:26:49.508Z",
    },
    {
        garageName: "Precision Auto",
        ownerName: "Frank Blue",
        servicesRequested: ["Brake Inspection"],
        tirePurchased: false,
        status: "Completed",
        requestedTime: "2024-10-08T11:26:49.508Z",
    },
    {
        garageName: "Affordable Auto",
        ownerName: "Grace Pink",
        servicesRequested: ["Tire Rotation", "Oil Change"],
        tirePurchased: true,
        status: "Pending",
        requestedTime: "2024-10-09T11:26:49.508Z",
    },
    {
        garageName: "Premier Garage",
        ownerName: "Hannah Gray",
        servicesRequested: ["Oil Change", "Brake Inspection"],
        tirePurchased: true,
        status: "Completed",
        requestedTime: "2024-09-10T11:26:49.508Z",
    },
];
